[package]
name = "aoc-2024"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.93"
num-traits = "0.2.19"
pathfinding = "4.12.0"
pest = "2.7.15"
pest_derive = "2.7.15"
regex = "1.11.1"

[profile.release]
lto = "thin"
