name: GitHub Pages Deploy

on:
  push:
    branches:
      - main

jobs:
  wasm-build:
    name: Wasm build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable
      - run: rustup target add wasm32-wasip1
      - run: cargo build --target wasm32-wasip1 --release
      - uses: actions/upload-artifact@v4
        with:
          name: wasm-release
          path: target/wasm32-wasip1/release/*.wasm
  site-build:
    name: Site build
    runs-on: ubuntu-latest
    needs: wasm-build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: wasm-release
          path: target/wasm32-wasip1/release
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
          cache-dependency-path: web-runner/pnpm-lock.yaml
      - run: cd web-runner && pnpm install
      - run: cd web-runner && pnpm build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: web-runner/dist
  pages-deploy:
    name: GitHub Pages deploy
    runs-on: ubuntu-latest
    needs: site-build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
